org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=300000
android.useAndroidX=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
